apiVersion: apps/v1
kind: Deployment
metadata:
  name: awsdep
spec:
 replicas: 3
 selector:
   matchLabels:
     name: appaws
 template:
   metadata:
     name: awspod
     labels:
       name: appaws
   spec:
     containers:
       - name: awscon
         image: gangadhariy/jenkube
         ports:
          - containerPort: 8080
